[build]
command = "ng build"
functions = "netlify/functions"
publish = "dist/weather/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

[[edge_functions]]
path = "angular-ssr"
function = "angular-ssr"